# Generated by Django 3.2.19 on 2023-07-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='People',
        ),
    ]
