# Generated by Django 3.2.19 on 2023-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_grades_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32)),
                ('c_girl_num', models.IntegerField(default=1)),
                ('c_boy_num', models.IntegerField(default=1)),
            ],
        ),
    ]
