# Generated by Django 3.2.19 on 2023-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=32)),
            ],
        ),
    ]
